sudo: false
dist: trusty
cache: bundler
language: ruby
deploy:
  provider: heroku
  api_key:
    secure: RB3vQcQN2bCEo2tGH8wBDTvSvOd75IHilMYezs7MbHTMcIohZEn3HYHzQHNGCFCGlJtlrYx8SDQxus3viRtwk6HM16P1Dp2tDCd8af6bmlhOu0wSKvuKLDx6JVedJz7HqGhjIFdSXdMyUK79meE9Xv4oJmsvKlMzf3PdBlD/zgU=
