development: &development
  database: bongloy_demo_development
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: bongloy_demo

test:
  <<: *development
  database: bongloy_demo_test

# This gets overriden by Heroku
production:
  <<: *development
